/* Automatically generated by "build-radpaths-h" */
#define LOGDIR		"/opt/hspgw/var/log/radius"
#define RADDBDIR	"/opt/hspgw/etc/raddb"
#define RUNDIR		"/opt/hspgw/var/run"
#define SBINDIR		"/opt/hspgw/sbin"
#define RADIR		"/opt/hspgw/var/log/radius/radacct"
